CREATE TABLE IF NOT EXISTS "dex_screener_pair" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone,
	"base_token_address" text,
	"base_token_symbol" text,
	"base_token_name" text,
	"fdv" double precision,
	"image_url" text,
	"twitter" text,
	"telegram" text,
	"website" text,
	"base_liquidity" double precision,
	"quote_liquidity" double precision,
	"usd_liquidity" double precision,
	"pair_address" text,
	"pair_created_at" timestamp with time zone,
	"price_change_h1" double precision,
	"price_change_h6" double precision,
	"price_change_h24" double precision,
	"price_change_5m" double precision,
	"price_native" double precision,
	"price_usd" double precision,
	"quote_token_address" text,
	"quote_token_symbol" text,
	"quote_token_name" text,
	"txns_h1" integer,
	"txns_h6" integer,
	"txns_h24" integer,
	"txns_5m" integer,
	"volume_h1" double precision,
	"volume_h6" double precision,
	"volume_h24" double precision,
	"volume_5m" double precision
);
