CREATE TABLE IF NOT EXISTS "pool_keys" (
	"id" text PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone,
	"base_mint" text NOT NULL,
	"quote_mint" text NOT NULL,
	"lp_mint" text NOT NULL,
	"base_decimals" integer NOT NULL,
	"quote_decimals" integer NOT NULL,
	"lp_decimals" integer NOT NULL,
	"version" integer NOT NULL,
	"program_id" text NOT NULL,
	"authority" text NOT NULL,
	"base_vault" text NOT NULL,
	"quote_vault" text NOT NULL,
	"open_orders" text NOT NULL,
	"target_order" text NOT NULL,
	"withdrawal_queue" text NOT NULL,
	"lp_vault" text NOT NULL,
	"market_version" integer NOT NULL,
	"market_program_id" text NOT NULL,
	"market_id" text NOT NULL,
	"market_authority" text NOT NULL,
	"market_base_vault" text NOT NULL,
	"market_quote_vault" text NOT NULL,
	"market_bids" text NOT NULL,
	"market_asks" text NOT NULL,
	"market_event_queue" text NOT NULL
);
